export const EMAIL_TEMPLATE_ACCOUNT_CANCEL_CTA = 'Come back anytime!';
export const EMAIL_TEMPLATE_ACCOUNT_CANCEL_HEADLINE = 'Account Canceled';
export const EMAIL_TEMPLATE_ACCOUNT_CANCEL_MAIN = {
  get: ({ accountName }) => `Sorry to see you go! "${accountName}" has been canceled. A prorated refund will be issued shortly. Feel free to contact us with any questions.`,
};
export const EMAIL_TEMPLATE_ACCOUNT_CANCEL_MAIN_FREE_TRIAL = {
  get: ({ accountName }) => `Sorry to see you go! "${accountName}" has been canceled. Because you canceled during the trial period - you will not be charged.`,
};
export const EMAIL_TEMPLATE_ACCOUNT_USER_ADDED_HEADLINE = `You're Added!`;
export const EMAIL_TEMPLATE_ACCOUNT_USER_ADDED_CTA = 'Manage your accounts here.';
export const EMAIL_TEMPLATE_ACCOUNT_USER_ADDED_MAIN = {
  get: ({ accountName }) => `You've been added to "${accountName}" Foo account.`,
};
export const EMAIL_TEMPLATE_ACCOUNT_USER_INVITED_HEADLINE = `You're Invited!`;
export const EMAIL_TEMPLATE_ACCOUNT_USER_INVITED_CTA = 'Accept the invitation by registering here.';
export const EMAIL_TEMPLATE_ACCOUNT_USER_INVITED_MAIN = {
  get: ({ accountName }) => `You've been invited to "${accountName}" Foo account.`,
};
export const EMAIL_TEMPLATE_EMAIL_CONFIRM = 'Please confirm your email address.';
export const EMAIL_TEMPLATE_EMAIL_CONFIRM_CTA = 'Navigate here to confirm.';
export const EMAIL_TEMPLATE_EMAIL_CONFIRM_HEADLINE = 'Email Confirm';
export const EMAIL_TEMPLATE_EMAIL_ALERT_CONFIRM_CTA = 'Navigate here to confirm.';
export const EMAIL_TEMPLATE_EMAIL_ALERT_CONFIRM_HEADLINE = 'Confirm';
export const EMAIL_TEMPLATE_EMAIL_ALERT_CONFIRM_MAIN = 'Please confirm this email as an alert for Foo. This email will be notified with status updates as they occur.';
export const EMAIL_TEMPLATE_ID_ACCOUNT_CANCEL = 'd-5d850cea0d6e4262aea1677d5a4e45dc';
export const EMAIL_TEMPLATE_ID_ACCOUNT_USER_ADDED = 'd-ff5d8e55aace43cca73583ac4e54ca81';
export const EMAIL_TEMPLATE_ID_ACCOUNT_USER_INVITED = 'd-5e995c467ff941dcbd5aae3a9f146b4f';
export const EMAIL_TEMPLATE_ID_ACCOUNT_USER_REMOVED_CONFIRMATION = 'd-cf4dbc9c87464cdab1a4f07da21ceccb';
export const EMAIL_TEMPLATE_ID_EMAIL_ALERT_CONFIRM = 'd-f0e2fe2890ed47b5811c20812587a1cb';
export const EMAIL_TEMPLATE_ID_EMAIL_CONFIRM = 'd-044e308ea69741c7b9349d9970ec48f6';
export const EMAIL_TEMPLATE_ID_INVITE_ACCEPTED = 'd-9620b0e881a0407facb3ee4904eda072';
export const EMAIL_TEMPLATE_ID_PAGE_HEALTH_ALERT_HEALTHY = 'd-0aef9ceb257e48dbbe5f83c7629cda9b';
export const EMAIL_TEMPLATE_ID_PAGE_HEALTH_ALERT_UNHEALTHY = 'd-eca574ba0dfa4fe59be8f29a2b32424d';
export const EMAIL_TEMPLATE_ID_PASSWORD_RESET = 'd-e4f89c8943d9436c95fe2aae3e07a312';
export const EMAIL_TEMPLATE_ID_REFUND_STATUS = 'd-a1dae5c4a12549c784eebd9f6ea8717b';
export const EMAIL_TEMPLATE_ID_SUBSCRIPTION_CREATED = 'd-2c0dbb1acd7045ae8ff7879015cbbd91';
export const EMAIL_TEMPLATE_ID_SUBSCRIPTION_PAYMENT_PAST_DUE = 'd-ae7346390e2c42b69414c51f725aace9';
export const EMAIL_TEMPLATE_ID_WELCOME = 'd-ccb4f0689c484dda8f2ffc3c41c9b649';
export const EMAIL_TEMPLATE_INVITE_ACCEPTED_CTA = 'See all users.';
export const EMAIL_TEMPLATE_INVITE_ACCEPTED_HEADLINE = 'Invite Accepted';
export const EMAIL_TEMPLATE_INVITE_ACCEPTED_MAIN = {
  get: ({ email }) => `${email} has accepted your invite!`,
};
export const EMAIL_TEMPLATE_PAGE_HEALTH_ALERT_HEALTHY_MAIN = {
  get: ({ pageName }) => `"${pageName}" page has recovered.`,
};
export const EMAIL_TEMPLATE_PAGE_HEALTH_ALERT_UNHEALTHY_MAIN = {
  get: ({ pageName }) => `"${pageName}" page has become unhealthy.`,
};
export const EMAIL_TEMPLATE_PAGE_HEALTH_ALERT_HEADLINE = 'Page Health Status';
export const EMAIL_TEMPLATE_PAGE_HEALTH_ALERT_CTA = 'Dashboard';
export const EMAIL_TEMPLATE_PAGE_HEALTH_ALERT_LINK_CTA = 'Visit the dashboard.';
export const EMAIL_TEMPLATE_PASSWORD_RESET_HEADLINE = 'Password Reset';
export const EMAIL_TEMPLATE_PASSWORD_RESET_CTA = 'Navigate here to reset your password.';
export const EMAIL_TEMPLATE_PASSWORD_RESET_MAIN = {
  get: ({ passwordResetDays }) => `You have ${passwordResetDays} days to reset your password.`,
};
export const EMAIL_TEMPLATE_REFUND_STATUS_CTA = 'Visit us anytime here.';
export const EMAIL_TEMPLATE_REFUND_STATUS_HEADLINE = 'Refund Status';
export const EMAIL_TEMPLATE_REFUND_STATUS_MAIN = {
  get: ({ refundAmount }) => `You were refunded $${refundAmount}.`,
};
export const EMAIL_TEMPLATE_SUBSCRIPTION_CREATED_CTA = 'Visit the dashboard.';
export const EMAIL_TEMPLATE_SUBSCRIPTION_CREATED_HEADLINE = 'Congrats!';
export const EMAIL_TEMPLATE_SUBSCRIPTION_CREATED_MAIN = {
  get: ({ price, trialDuration }) => `You've successfully created an account subscription. The free trial is ${trialDuration}. If you don't cancel before the end of the trial - you'll be charged ${price} on that day and every month until you cancel. You can cancel anytime in the account section. Cancellations are refunded a prorated amount. If you cancel before the free trial end you won't be charged at all!`,
};
export const EMAIL_TEMPLATE_SUBSCRIPTION_PAYMENT_PAST_DUE_CTA = 'You can update or add a new payment method in billing.';
export const EMAIL_TEMPLATE_SUBSCRIPTION_PAYMENT_PAST_DUE_HEADLINE = 'Payment Status';
export const EMAIL_TEMPLATE_SUBSCRIPTION_PAYMENT_PAST_DUE_MAIN = 'Your subscription payment is past due and therefore your account has been switched to "read only" mode until resolved.';
export const EMAIL_TEMPLATE_WELCOME_HEADLINE = 'Welcome!';
export const EMAIL_TEMPLATE_WELCOME_MAIN = 'Thanks for registering.';
export const ERROR_ACCOUNT_CREATE = 'Error creating account.';
export const ERROR_ACCOUNT_CREATE_NO_CREDIT = 'No account credits.';
export const ERROR_ACCOUNT_FREE_ALREADY_USED = 'Only one free account allowed.';
export const ERROR_ACCOUNT_GET_SUBSCRIPTION = 'Error getting account subscription.';
export const ERROR_ACCOUNT_IS_READ_ONLY = 'This account is read only.';
export const ERROR_ACCOUNT_IS_READ_ONLY_USER_EMAIL_UNCONFIRMED = 'This account is read only until the email needs to be confirmed. Go to settings page for help.';
export const ERROR_ACCOUNT_REMOVE_USER = 'Error removing account user.';
export const ERROR_ACCOUNT_UPGRADE = 'Error upgrading.';
export const ERROR_ACCOUNT_SUBSCRIPTION_PAYMENT_UPDATE = 'Error updating the payment method.';
export const ERROR_ACCOUNT_UPDATE_USER = 'Error updating account user.';
export const ERROR_ACCOUNT_UPDATE_FROM_SUBSCRIPTION = 'Error updating account from subscription.';
export const ERROR_ALERT_CREATE = 'Error creating alert.';
export const ERROR_ALERT_EMAIL_CONFIRMATION = 'Error confirming email.';
export const ERROR_ALERT_EMAIL_CONFIRMATION_RESEND = 'Error resending confirmation email.';
export const ERROR_ALERT_EMAIL_CONFIRMATION_RESEND_NOT_FOUND = 'Error resending confirmation email - alert not found.';
export const ERROR_ALERT_INVALID_SLACK_URL = 'Invalid Slack webhook url.';
export const ERROR_ALERT_REMOVE = 'Error removing alert.';
export const ERROR_ALERT_UPDATE = 'Error updating alert.';
export const ERROR_ALERTS_MAX_REACHED = 'Maximum alerts reached.';
export const ERROR_AUTHENTICATION_EMAIL_TAKEN = 'That email is taken.';
export const ERROR_AUTHENTICATION_FORBIDDEN = 'The user is forbidden.';
export const ERROR_AUTHENTICATION_INVITE_EXPIRED = 'That invite is expired.';
export const ERROR_AUTHENTICATION_INVALID_PASSWORD = 'Password should be at least 8 characters.';
export const ERROR_AUTHENTICATION_NO_USER = 'That user does not exist.';
export const ERROR_AUTHENTICATION_WRONG_PASSWORD = 'Wrong password.';
export const ERROR_BRAINTREE_CREATE_SALE_TRANSACTION = 'Error creating sale transaction.';
export const ERROR_BRAINTREE_CREATE_SUBSCRIPTION = 'Error creating subscription.';
export const ERROR_BRAINTREE_GET_CLIENT_TOKEN = 'Error getting client token.';
export const ERROR_BRAINTREE_GET_SUBSCRIPTION = 'Error getting subscription.';
export const ERROR_BRAINTREE_TRANSACTION_DECLINE = 'There was a problem processing your credit card, please double check your payment information and try again';
export const ERROR_DISABLED = 'Disabled.';
export const ERROR_EMAIL_ALREADY_TAKEN = 'That email is already taken.';
export const ERROR_FLAGGED_FOR_REMOVAL = 'This account has been deleted.';
export const ERROR_GENERIC = 'Sorry, something went wrong.';
export const ERROR_INVITATION_CREATE = 'Error creating invitation.';
export const ERROR_INVITATION_MAX_USERS = 'Max user limit has been reached for this account. If you have outdated pending notifications - try deleting those.';
export const ERROR_MISSING_REQUIRED_FIELDS = 'Missing required fields.';
export const ERROR_NAVIGATION_TIMEOUT = {
  get: ({ puppeteerDefaultTimeout }) => `The request took longer than the allowed ${puppeteerDefaultTimeout}ms.`,
};
export const ERROR_PAGE_CREATE = 'Error creating page.';
export const ERROR_PAGE_MAX_PAGES = 'Max page limit has been reached for this account.';
export const ERROR_PAGE_MISSING = 'This page does not exist.';
export const ERROR_PAGE_UPDATE = 'Error updating page.';
export const ERROR_PAGE_REMOVE = 'Error removing page.';
export const ERROR_REMOVE = 'Error removing.';
export const ERROR_SLACK_CREATE_ACCOUNT_ALERT = 'Error creating account alert';
export const ERROR_SLACK_INVALID_OAUTH_ACCESS_RESPONSE = 'Authentication failed.';
export const ERROR_SLACK_NATIVE = 'Slack responded with an error.';
export const ERROR_UNAUTHENTICATED = 'You are unauthenticated, please login.';
export const ERROR_UNHANDLED_EXCEPTION = 'Unhandled error.';
export const ERROR_UPDATE = 'Error updating.';
export const ERROR_USER_ACCOUNT_SUSPENDED = 'Your account is pending attention by us. Please contact us if you need more info.';
export const ERROR_USER_CREATE_PASSWORD_RESET_TOKEN = 'Error creating reset token.';
export const ERROR_USER_CREATE_PASSWORD_RESET_TOKEN_NO_USER = 'No users found with that email.';
export const ERROR_USER_EMAIL_CONFIRMATION_SENT = 'Error sending confirmation email.';
export const ERROR_USER_LOGIN = 'Error logging in.';
export const ERROR_USER_REGISTER = 'Error registering.';
export const ERROR_USER_REGISTER_ACCOUNT_CREATION = 'Error creating account after registering.';
export const ERROR_USER_RESET_PASSWORD = 'Error resetting password.';
export const ERROR_USER_RESET_PASSWORD_INVALID_PASSWORD = 'Password should be at least 8 characters.';
export const ERROR_USER_RESET_PASSWORD_NO_USER_TOKEN = 'No user exists with that email and token.';
export const ERROR_USER_RESET_PASSWORD_TOKEN_EXPIRED = 'Password reset token has expired.';
export const INVALID_EMAIL = 'Invalid email.';
export const SUCCESS_ACCOUNT_CREATE = 'Account created!';
export const SUCCESS_ACCOUNT_REMOVE_USER = 'Account user removed!';
export const SUCCESS_ACCOUNT_SUBSCRIPTION_PAYMENT_UPDATE = 'Payment method updated!';
export const SUCCESS_ACCOUNT_UPGRADE = 'Upgrade success!';
export const SUCCESS_ACCOUNT_UPDATE_USER = 'Account user updated!';
export const SUCCESS_ALERT_CREATE = 'Alert created!';
export const SUCCESS_ALERT_EMAIL_CONFIRMATION = 'Confirmed successfully!';
export const SUCCESS_ALERT_EMAIL_CONFIRMATION_RESEND = 'Confirmation email resent successfully!';
export const SUCCESS_ALERT_UPDATE = 'Alert updated!';
export const SUCCESS_ALERT_REMOVE = 'Alert removed!';
export const SUCCESS_GENERIC = 'Success!';
export const SUCCESS_INVITATION_CREATE = 'Invitation created!';
export const SUCCESS_PAGE_CREATE = 'Page created!';
export const SUCCESS_PAGE_UPDATE = 'Page updated!';
export const SUCCESS_PAGE_REMOVE = 'Page removed!';
export const SUCCESS_REMOVE = 'Removed!';
export const SUCCESS_UPDATE = 'Updated!';
export const SUCCESS_USER_CREATE_PASSWORD_RESET_TOKEN = 'You will receive an email with reset instructions shortly!';
export const SUCCESS_USER_EMAIL_CONFIRMATION_SENT = 'Confirmation code sent!';
export const SUCCESS_USER_LOGIN = 'Sucess!';
export const SUCCESS_USER_LOGOUT = 'Logged out!';
